# Generated by Django 5.1.4 on 2026-08-19 14:18

import django.db.models.deletion
import school.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=150)),
                ('realtime_reasoning_effort', models.CharField(choices=[('low', 'Low — più rapido'), ('medium', 'Medium — bilanciato'), ('high', 'High — più approfondito')], default='low', max_length=10)),
                ('learning_context', models.TextField(blank=True, max_length=1000, validators=[school.models.validate_max_100_words])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
