# Generated by Django 5.1.4 on 2026-08-19 14:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def initialize_access_and_cache(apps, schema_editor):
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    Subscription = apps.get_model('school', 'Subscription')
    UserProfile = apps.get_model('school', 'UserProfile')
    Course = apps.get_model('school', 'Course')

    for user_id in User.objects.values_list('id', flat=True):
        Subscription.objects.get_or_create(user_id=user_id)
        user = User.objects.get(id=user_id)
        display_name = (f"{user.first_name} {user.last_name}".strip()
                        or (user.email.split('@', 1)[0] if user.email else user.username))
        UserProfile.objects.get_or_create(
            user_id=user_id,
            defaults={'display_name': display_name},
        )

    used_keys = set()
    for course in Course.objects.order_by('id'):
        key = ' '.join((course.normalized_subject or course.title).casefold().split())
        if key and key not in used_keys:
            course.cache_key = key
            course.save(update_fields=['cache_key'])
            used_keys.add(key)


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='cache_key',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='lessonsession',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_invoice_id', models.CharField(max_length=255, unique=True)),
                ('amount_cents', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='eur', max_length=3)),
                ('status', models.CharField(max_length=30)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(blank=True, choices=[('base', 'Base — €19,99/mese'), ('premium', 'Premium — €45/mese')], max_length=10)),
                ('status', models.CharField(choices=[('inactive', 'Non attivo'), ('incomplete', 'Incompleto'), ('trialing', 'In prova'), ('active', 'Attivo'), ('past_due', 'Pagamento scaduto'), ('unpaid', 'Non pagato'), ('canceled', 'Annullato')], default='inactive', max_length=20)),
                ('stripe_customer_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('stripe_subscription_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('curriculum', 'Generazione corso'), ('course_cache', 'Corso dalla cache'), ('realtime_session', 'Sessione Realtime'), ('realtime_response', 'Risposta Realtime'), ('quiz', 'Quiz'), ('illustration', 'Illustrazione')], max_length=30)),
                ('request_count', models.PositiveIntegerField(default=1)),
                ('input_tokens', models.PositiveBigIntegerField(default=0)),
                ('output_tokens', models.PositiveBigIntegerField(default=0)),
                ('total_tokens', models.PositiveBigIntegerField(default=0)),
                ('image_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(initialize_access_and_cache, migrations.RunPython.noop),
    ]
