# Generated by Django 5.1.4 on 2026-08-20 05:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def backfill_user_courses(apps, schema_editor):
    UserCourse = apps.get_model('school', 'UserCourse')
    CoursePurchase = apps.get_model('school', 'CoursePurchase')
    LessonSession = apps.get_model('school', 'LessonSession')
    now = django.utils.timezone.now()
    history = {}

    for purchase in CoursePurchase.objects.filter(status='paid').iterator():
        key = (purchase.user_id, purchase.course_id)
        accessed_at = purchase.purchased_at or purchase.updated_at or now
        history[key] = {
            'user_id': purchase.user_id,
            'course_id': purchase.course_id,
            'last_accessed_at': accessed_at,
            'last_lesson_id': None,
        }

    sessions = (
        LessonSession.objects.filter(student_id__isnull=False)
        .select_related('lesson')
        .order_by('started_at', 'id')
    )
    for session in sessions.iterator():
        key = (session.student_id, session.lesson.course_id)
        accessed_at = session.ended_at or session.started_at or now
        existing = history.get(key)
        if existing is None or accessed_at >= existing['last_accessed_at']:
            history[key] = {
                'user_id': session.student_id,
                'course_id': session.lesson.course_id,
                'last_accessed_at': accessed_at,
                'last_lesson_id': session.lesson_id,
            }

    UserCourse.objects.bulk_create(UserCourse(**values) for values in history.values())


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_pagevisit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('hidden_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_history', to='school.course')),
                ('last_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='school.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_accessed_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'course'), name='unique_user_course_history')],
            },
        ),
        migrations.RunPython(backfill_user_courses, migrations.RunPython.noop),
    ]
